// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "",
    "aws_cognito_identity_pool_id": "",
    "aws_cognito_region": "",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip_dev",
            "alias": "$LATEST",
            "region": ""
        }
    ],
    "aws_appsync_graphqlEndpoint": "",
    "aws_appsync_region": "",
    "aws_appsync_authenticationType": "",
    "aws_appsync_apiKey": ""
};


export default awsmobile;
